/** user text throughout the app */

const userText = {
	Q1: "\nPLEASE, TYPE A SEARCH TERM FOR A BOOK: ",
	Q2: "\nTO ADD TO YOUR READING LIST, ENTER BOOK ID: ",
	Q3: "\nRETRIEVE YOUR READING LIST? y/n : ",
	READ_LIST: "reading-list.txt",
	BOOK_NAME_ERR: "***OOPS. NO BOOKS AVAILABLE WITH THAT NAME.***",
	ID_ERR: "***OOPS. BOOK ID IS INVALID.***",
	FINAL_MSG: "\nBYE BYE!!!",
	NO_INPUT: "***OOPS, WE DO NOT RECOGNIZE YOUR SEARCH TERM. PLEASE, TRY AGAIN.***",
	BOOK_EXISTS: "***OOPS, THIS BOOK IS ALREADY IN YOUR READING LIST.***",
	NEW_BOOK: "YOUR BOOK WAS SUCCESSFULLY SAVED."
};

module.exports = userText;
